version: '3'
services:
  frontoffice:
    image: palomitablog_frontoffice
    container_name: palomitablog_frontoffice_test
    build:
      context: ../
      dockerfile: ./docker/frontoffice.dockerFile
    command: npm run test:watch
    volumes:
      - "../frontoffice:/palomitablog/frontoffice"
    environment:
      - NODE_ENV=test
